database:
  host: localhost
  port: 3306
  dbName: xsguilds
  user: root
  password: 992545tai

redis:
  host: localhost
  port: 6379
  password: ''

auto-saved: 60 #in seconds

create_guild_price: 1000

guilds-group:
  survival:
    - survival/01
    - survival/02
  lobby:
    - lobby/01
  skyblock:
    - skyblock/01

guild_configuration:
  balance_capacity:
    main:
      level_1: 5000
      level_2: 10000
      level_3: 15000
      level_4: 20000
    sub:
      level_1: 10000
      level_2: 15000
      level_3: 20000
      level_4: 25000
  home:
    sub:
      level_1: 1
      level_2: 1
      level_3: 2
      level_4: 2
  members:
    main:
      level_1: 10
      level_2: 15
      level_3: 20
      level_4: 25

upgrades_configuration:
  main:
    level_2:
      points: 1000
    level_3:
      points: 1500
    level_4:
      points: 2000
  sub:
    level_2:
      points: 500
      coins: 300
    level_3:
      points: 700
      coins: 400
    level_4:
      points: 1400
      coins: 800