package net.xsapi.panat.xsguildclient.utils;

public enum XSDATA_TYPE {

    CREATE,LOAD_DATA,REQ_DATA,DEBUG,REQ_GUILD,GET_GUILD,DISBAND,UPDATED,INVITE,INVITE_RETURN,INVITE_GET,INVITE_RESPOND,INVITE_RESPOND_RETURN,UPDATE_GUILD,FORCE_LOAD_ALL,LEAVE_GUILD,KICK_REQUEST,KICK_RESPOND
}
