redis:
  host: localhost
  port: 6379
  password: ''

configuration:
  server: lobby/01
  format:
    nonGuild: "<dark_gray>(<red>ไม่มีกิลด์<dark_gray>)"
    default: "<dark_gray>(<green><bold>Lv.</bold>%guild_level% <white>%guild_name%<dark_gray>)"