package net.xsapi.panat.xsguildbungee.utils;

public enum XSDATA_TYPE {

    CREATE,LOAD_DATA,REQ_DATA,DEBUG,REQ_GUILD,GET_GUILD,DISBAND,UPDATED,INVITE,INVITE_RETURN,INVITE_GET,INVITE_RESPOND,INVITE_RESPOND_RETURN,UPDATE_GUILD,FORCE_LOAD_ALL,LEAVE_GUILD,KICK_REQUEST,KICK_RESPOND
    ,TRANSFER_LEADER_REQUEST,TRANSFER_LEADER_RESPOND,PROMOTE_REQUEST,PROMOTE_RESPOND,DEMOTE_REQUEST,DEMOTE_RESPOND,DEPOSIT_POINTS,DEPOSIT_COINS,WITHDRAW_COINS,WITHDRAW_POINTS,WITHDRAW_COINS_RESPOND,WITHDRAW_POINTS_RESPOND
    ,UNINVITE,UNINVITE_RESPOND,REMOVE_GUILD,GUILD_MESSAGE_SENT,GUILD_MESSAGE_RESPOND,GUILD_CHAT_CHANGE_STATE,SETHOME,DELHOME,TELEPORT_TO_HOME,SENT_UPGRADES_INFO,UPGRADE_REQ,UPGRADE_RES
}
